:- dynamic usuari/14.

usuari(capquadrat, "Cap", "Quadrat", 15, ['Classics', 'Fiction', 'Poetry', 'Mythology', 'Fantasy', 'School'], [posteriors, 1200, anteriors, 2023], [extensio_min, 0, extensio_max, 2000], [], ['Ernest Hemingway', 'J.K. Rowling', 'Maurice Sendak'], ["German", "English"], ['Homer'], ['London', 'New York', 'Hogwarts'], ['Fiction', 'Fantasy', 'Classics'], []).
usuari(janaventura, 'Jana', 'Ventura', 12, ['Adventure', 'LGBT', 'Mystery'], [posteriors, 1000, anteriors, 3000], [extensio_min, 250, extensio_max, 350], [], ['Laura Gallego Garc�\u00ADa'], ["English", "Spanish"], [], ['Washington'], [], []).
usuari(ainasans, 'Aina', 'Sans', 30, ['LGBT', 'Romance', 'Philosophy', 'Paranormal'], [posteriors, 1900, anteriors, 2023], [extensio_min, 50, extensio_max, 600], [], [], ["English", "Spanish"], [], ['Spain'], [], []).
usuari(markusurban, 'Markus', 'Urban', 18, ['Mystery', 'Philosophy', 'Science Fiction', 'Adventure'], [posteriors, 1900, anteriors, 2023], [extensio_min, 0, extensio_max, 10000], [], ['J.K. Rowling'], ["German"], ['Ken Follett'], [], [], []).
usuari(emmagarcia, 'Emma', 'Garcia', 28, ['Fiction', 'Fantasy', 'Juvenile', 'Romance', 'Drama', 'Science Fiction', 'Contemporary'], [posteriors, 2000, anteriors, 2023], [extensio_min, 300, extensio_max, 400], [], ['José Antonio Cotrina'], ["English", "Spanish", "French"], [], [], [], []).
usuari(carbassot, 'En Carbassot', 'fa el que pot', 11, ['Adventure', 'Fantasy', 'Fiction', 'Science Fiction', 'Comedy', 'Juvenile', 'Humor', 'Magic', 'Vampires', 'Novels', 'Animals', 'Short Stories'], [posteriors, 2000, anteriors, 2023], [extensio_min, 100, extensio_max, 300], [], [], ["English", "Spanish", "French"], [], ['Farm'], ['History'], []).
usuari(ramiro, 'Ramiro', 'Amo', 34, ['Crime', 'Dystopia', 'Epic Fantasy', 'Comedy', 'Humor', 'Adventure', 'Novels', 'Classics', 'Animals'], [posteriors, 1900, anteriors, 2023], [extensio_min, 100, extensio_max, 300], [], [], ["English", "Spanish"], [], [], ['Love', 'Classics'], []).
usuari(sirio, 'Sirio', 'Gos', 12, ['Adventure', 'Romance', 'Magic', 'Urban Fantasy', 'Gothic', 'Historical', 'Novels'], [posteriors, 1200, anteriors, 2023], [extensio_min, 120, extensio_max, 500], [], [], ["English", "Spanish"], [], ['Paris'], [], []).
usuari(sarsadenes, 'Testimoni', ' Sarsanedes', 59, ['Fiction', 'Crime', 'Epic Fantasy', 'Historical', 'Literature', 'Philosophy', 'Historical Fiction', 'Novels', 'Classics', 'Plays', 'Poetry'], [posteriors, 1900, anteriors, 2010], [extensio_min, 350, extensio_max, 650], [], [], ["English", "Spanish"], [], [], ['Nonfiction'], []).
usuari(rellinas, 'Testimoni', 'Rellinas', 11, ['Adventure', 'Fantasy', 'Fantasy', 'Juvenile', 'Vampires', 'Novels', 'Animals', 'Biography', 'Short Stories'], [posteriors, 1200, anteriors, 2020], [extensio_min, 1200, extensio_max, 300], [], [], ["Spanish", "French"], [], ['Texas', 'Italy'], ['Magic'], []).
usuari(puigdellivol, 'Testimoni', 'Puigdellivol', 20, ['Crime', 'Suspense', 'Thriller', 'Mystery', 'Paranormal', 'Novels'], [posteriors, 1990, anteriors, 2023], [extensio_min, 300, extensio_max, 500], [], ['L.M. Montgomery'], ["English", "Spanish"], [], [], [], []).
usuari(arnaucosta, 'Arnau', 'Costa', 20, ['Adventure', 'Fiction', 'Science Fiction', 'Fantasy', 'Historical', 'Juvenile', 'Magic', 'Historical Fiction', 'Novels'], [posteriors, 1900, anteriors, 2023], [extensio_min, 100, extensio_max, 2000], [], [], ["Spanish", "English"], ['J.R.R. Tolkien', 'J.K. Rowling', 'G.R.R. Martin', 'Frank Herbert'], [], ['Comics'], []).
usuari(peresclau, "Pere", "Esclau", 17, ['Novels', 'Horror', 'Nordic Noir', 'Fantasy', 'Paranormal', 'Romance', 'Drama'], [posteriors, 1800, anteriors, 2023], [extensio_min, 100, extensio_max, 400], [], ['Ernest Hemingway', 'J.K. Rowling', 'Maurice Sendak'], ["German", "English"], ['Albus Dumbledore'], ['London', 'New York', 'Hogwarts'], ['Fantasy'], []).
usuari(albins, 'Alba', 'Ramionet', 17, ['Adventure', 'Fantasy', 'Fiction', 'Juvenile', 'Comedy', 'Philosophy', 'Romance', 'Novels', 'Short Stories', 'Animals'], [posteriors, 1990, anteriors, 2023], [extensio_min, 200, extensio_max, 400], [], [], ["Spanish"], [], [], ['Drama'], []).
usuari(annallopis, 'Anna', 'Llopis', 32, ['Fiction', 'Novels', 'Fantasy', 'Spanish Literature'], [posteriors, 2000, anteriors, 2023], [extensio_min, 200, extensio_max, 350], ['Hogwarts', 'Paris'], ['Audrey Niffenegger', 'Douglas Adams'], ["German", "English"], ['J.R.R. Tolkien', 'J.K. Rowling'], ['London', 'New York'], ['Vampires', 'Comedy'], []).
usuari(pardimoll, 'Pardimoll', 'és un Carmadec', 22, ['Adventure', 'Fiction', 'Crime', 'Historical', 'Thriller', 'Historical Fiction', 'Suspense', 'Novels', 'Classics', 'Animals', 'Poetry'], [posteriors, 1950, anteriors, 2010], [extensio_min, 350, extensio_max, 500], si, ['Cormac McCarthy'], ["English", "French", "German"], ['Veronica Roth'], [], ['Philosophy', 'Religion', 'Vampires'], []).
usuari(johnmccarthy, "John", "McCarthy", 84, ['Classics', 'Fiction', 'Poetry', 'Mythology', 'Fantasy', 'School'], [posteriors, 1200, anteriors, 2023], [extensio_min, 50, extensio_max, 2000], [], ['Ernest Hemingway', 'Maurice Sendak'], ["German", "English"], ['Homer'], ['London'], ['Fiction'], []).
usuari(alanturing, "Alan", "Turing", 41, ['Novels', 'Horror', 'Fantasy', 'Paranormal', 'Romance', 'Drama'], [posteriors, 1800, anteriors, 2023], [extensio_min, 100, extensio_max, 400], ['London', 'New York'], ['J.K. Rowling'], ["German", "English"], [], [], ['Fantasy'], []).

